<?php
/**
 * ItemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recomax REST API
 *
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ItemApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addItemAtUsingPUT
     *
     * Add item.
     *
     */
    public function testAddItemAtUsingPUT()
    {
    }

    /**
     * Test case for addItemUsingPOST
     *
     * Add item.
     *
     */
    public function testAddItemUsingPOST()
    {
    }

    /**
     * Test case for deleteItemUsingDELETE
     *
     * Delete item.
     *
     */
    public function testDeleteItemUsingDELETE()
    {
    }

    /**
     * Test case for gettemUsingGET
     *
     * Get item.
     *
     */
    public function testGettemUsingGET()
    {
    }

    /**
     * Test case for listtemUsingGET
     *
     * List items.
     *
     */
    public function testListtemUsingGET()
    {
    }

    /**
     * Test case for updateItemUsingPOST
     *
     * Update item.
     *
     */
    public function testUpdateItemUsingPOST()
    {
    }
}
