<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recomax REST API
 *
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addUserUsingPOST
     *
     * Add User.
     *
     */
    public function testAddUserUsingPOST()
    {
    }

    /**
     * Test case for addUserUsingPUT
     *
     * Add User.
     *
     */
    public function testAddUserUsingPUT()
    {
    }

    /**
     * Test case for deleteUserUsingDELETE
     *
     * Delete User.
     *
     */
    public function testDeleteUserUsingDELETE()
    {
    }

    /**
     * Test case for getSegmentsUsingGET
     *
     * Get User List.
     *
     */
    public function testGetSegmentsUsingGET()
    {
    }

    /**
     * Test case for getUserUsingGET
     *
     * Get User.
     *
     */
    public function testGetUserUsingGET()
    {
    }

    /**
     * Test case for listUsersUsingGET
     *
     * List Users.
     *
     */
    public function testListUsersUsingGET()
    {
    }

    /**
     * Test case for updateUserUsingPOST
     *
     * User item.
     *
     */
    public function testUpdateUserUsingPOST()
    {
    }
}
