<?php
/**
 * RecommendationApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recomax REST API
 *
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * RecommendationApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RecommendationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation queryItemUsingGET
     *
     * Get Recommendations for items
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     * @param  int $start start (optional, default to 0)
     * @param  int $page_size pageSize (optional, default to 10)
     * @param  string $sort_field sortField (optional)
     * @param  string $sort_type sortType (optional, default to asc)
     * @param  string $token token (optional)
     * @param  string $did did (optional)
     * @param  string $user user (optional)
     * @param  string[] $fq fq (optional)
     * @param  string $event event (optional, default to ON_QUERY)
     * @param  string $sb sb (optional, default to false)
     * @param  string $callback callback (optional)
     * @param  string $uid_cookie uidCookie (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\RecomResult
     */
    public function queryItemUsingGET($api_key, $id, $start = '0', $page_size = '10', $sort_field = null, $sort_type = 'asc', $token = null, $did = null, $user = null, $fq = null, $event = 'ON_QUERY', $sb = 'false', $callback = null, $uid_cookie = null)
    {
        list($response) = $this->queryItemUsingGETWithHttpInfo($api_key, $id, $start, $page_size, $sort_field, $sort_type, $token, $did, $user, $fq, $event, $sb, $callback, $uid_cookie);
        return $response;
    }

    /**
     * Operation queryItemUsingGETWithHttpInfo
     *
     * Get Recommendations for items
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     * @param  int $start start (optional, default to 0)
     * @param  int $page_size pageSize (optional, default to 10)
     * @param  string $sort_field sortField (optional)
     * @param  string $sort_type sortType (optional, default to asc)
     * @param  string $token token (optional)
     * @param  string $did did (optional)
     * @param  string $user user (optional)
     * @param  string[] $fq fq (optional)
     * @param  string $event event (optional, default to ON_QUERY)
     * @param  string $sb sb (optional, default to false)
     * @param  string $callback callback (optional)
     * @param  string $uid_cookie uidCookie (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\RecomResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function queryItemUsingGETWithHttpInfo($api_key, $id, $start = '0', $page_size = '10', $sort_field = null, $sort_type = 'asc', $token = null, $did = null, $user = null, $fq = null, $event = 'ON_QUERY', $sb = 'false', $callback = null, $uid_cookie = null)
    {
        $returnType = '\Swagger\Client\Model\RecomResult';
        $request = $this->queryItemUsingGETRequest($api_key, $id, $start, $page_size, $sort_field, $sort_type, $token, $did, $user, $fq, $event, $sb, $callback, $uid_cookie);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RecomResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation queryItemUsingGETAsync
     *
     * Get Recommendations for items
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     * @param  int $start start (optional, default to 0)
     * @param  int $page_size pageSize (optional, default to 10)
     * @param  string $sort_field sortField (optional)
     * @param  string $sort_type sortType (optional, default to asc)
     * @param  string $token token (optional)
     * @param  string $did did (optional)
     * @param  string $user user (optional)
     * @param  string[] $fq fq (optional)
     * @param  string $event event (optional, default to ON_QUERY)
     * @param  string $sb sb (optional, default to false)
     * @param  string $callback callback (optional)
     * @param  string $uid_cookie uidCookie (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function queryItemUsingGETAsync($api_key, $id, $start = '0', $page_size = '10', $sort_field = null, $sort_type = 'asc', $token = null, $did = null, $user = null, $fq = null, $event = 'ON_QUERY', $sb = 'false', $callback = null, $uid_cookie = null)
    {
        return $this->queryItemUsingGETAsyncWithHttpInfo($api_key, $id, $start, $page_size, $sort_field, $sort_type, $token, $did, $user, $fq, $event, $sb, $callback, $uid_cookie)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation queryItemUsingGETAsyncWithHttpInfo
     *
     * Get Recommendations for items
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     * @param  int $start start (optional, default to 0)
     * @param  int $page_size pageSize (optional, default to 10)
     * @param  string $sort_field sortField (optional)
     * @param  string $sort_type sortType (optional, default to asc)
     * @param  string $token token (optional)
     * @param  string $did did (optional)
     * @param  string $user user (optional)
     * @param  string[] $fq fq (optional)
     * @param  string $event event (optional, default to ON_QUERY)
     * @param  string $sb sb (optional, default to false)
     * @param  string $callback callback (optional)
     * @param  string $uid_cookie uidCookie (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function queryItemUsingGETAsyncWithHttpInfo($api_key, $id, $start = '0', $page_size = '10', $sort_field = null, $sort_type = 'asc', $token = null, $did = null, $user = null, $fq = null, $event = 'ON_QUERY', $sb = 'false', $callback = null, $uid_cookie = null)
    {
        $returnType = '\Swagger\Client\Model\RecomResult';
        $request = $this->queryItemUsingGETRequest($api_key, $id, $start, $page_size, $sort_field, $sort_type, $token, $did, $user, $fq, $event, $sb, $callback, $uid_cookie);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'queryItemUsingGET'
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     * @param  int $start start (optional, default to 0)
     * @param  int $page_size pageSize (optional, default to 10)
     * @param  string $sort_field sortField (optional)
     * @param  string $sort_type sortType (optional, default to asc)
     * @param  string $token token (optional)
     * @param  string $did did (optional)
     * @param  string $user user (optional)
     * @param  string[] $fq fq (optional)
     * @param  string $event event (optional, default to ON_QUERY)
     * @param  string $sb sb (optional, default to false)
     * @param  string $callback callback (optional)
     * @param  string $uid_cookie uidCookie (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function queryItemUsingGETRequest($api_key, $id, $start = '0', $page_size = '10', $sort_field = null, $sort_type = 'asc', $token = null, $did = null, $user = null, $fq = null, $event = 'ON_QUERY', $sb = 'false', $callback = null, $uid_cookie = null)
    {
        // verify the required parameter 'api_key' is set
        if ($api_key === null || (is_array($api_key) && count($api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_key when calling queryItemUsingGET'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling queryItemUsingGET'
            );
        }

        $resourcePath = '/{apiKey}/recommendations/items/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($sort_field !== null) {
            $queryParams['sortField'] = ObjectSerializer::toQueryValue($sort_field);
        }
        // query params
        if ($sort_type !== null) {
            $queryParams['sortType'] = ObjectSerializer::toQueryValue($sort_type);
        }
        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }
        // query params
        if ($did !== null) {
            $queryParams['did'] = ObjectSerializer::toQueryValue($did);
        }
        // query params
        if ($user !== null) {
            $queryParams['user'] = ObjectSerializer::toQueryValue($user);
        }
        // query params
        if (is_array($fq)) {
            $queryParams['fq'] = $fq;
        } else
        if ($fq !== null) {
            $queryParams['fq'] = ObjectSerializer::toQueryValue($fq);
        }
        // query params
        if ($event !== null) {
            $queryParams['event'] = ObjectSerializer::toQueryValue($event);
        }
        // query params
        if ($sb !== null) {
            $queryParams['sb'] = ObjectSerializer::toQueryValue($sb);
        }
        // query params
        if ($callback !== null) {
            $queryParams['callback'] = ObjectSerializer::toQueryValue($callback);
        }

        // path params
        if ($api_key !== null) {
            $resourcePath = str_replace(
                '{' . 'apiKey' . '}',
                ObjectSerializer::toPathValue($api_key),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($uid_cookie)) {
            $_tempBody = $uid_cookie;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation recommendForUserUsingGET
     *
     * Get Recommendations for user
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\RecomResult
     */
    public function recommendForUserUsingGET($api_key, $id)
    {
        list($response) = $this->recommendForUserUsingGETWithHttpInfo($api_key, $id);
        return $response;
    }

    /**
     * Operation recommendForUserUsingGETWithHttpInfo
     *
     * Get Recommendations for user
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\RecomResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function recommendForUserUsingGETWithHttpInfo($api_key, $id)
    {
        $returnType = '\Swagger\Client\Model\RecomResult';
        $request = $this->recommendForUserUsingGETRequest($api_key, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RecomResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation recommendForUserUsingGETAsync
     *
     * Get Recommendations for user
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recommendForUserUsingGETAsync($api_key, $id)
    {
        return $this->recommendForUserUsingGETAsyncWithHttpInfo($api_key, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation recommendForUserUsingGETAsyncWithHttpInfo
     *
     * Get Recommendations for user
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recommendForUserUsingGETAsyncWithHttpInfo($api_key, $id)
    {
        $returnType = '\Swagger\Client\Model\RecomResult';
        $request = $this->recommendForUserUsingGETRequest($api_key, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'recommendForUserUsingGET'
     *
     * @param  string $api_key apiKey (required)
     * @param  string $id id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function recommendForUserUsingGETRequest($api_key, $id)
    {
        // verify the required parameter 'api_key' is set
        if ($api_key === null || (is_array($api_key) && count($api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_key when calling recommendForUserUsingGET'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling recommendForUserUsingGET'
            );
        }

        $resourcePath = '/{apiKey}/recommendations/users/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($api_key !== null) {
            $resourcePath = str_replace(
                '{' . 'apiKey' . '}',
                ObjectSerializer::toPathValue($api_key),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
