<?php
/**
 * LocaleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recomax REST API
 *
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LocaleTest Class Doc Comment
 *
 * @category    Class
 * @description Locale
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocaleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Locale"
     */
    public function testLocale()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "display_country"
     */
    public function testPropertyDisplayCountry()
    {
    }

    /**
     * Test attribute "display_language"
     */
    public function testPropertyDisplayLanguage()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "display_script"
     */
    public function testPropertyDisplayScript()
    {
    }

    /**
     * Test attribute "display_variant"
     */
    public function testPropertyDisplayVariant()
    {
    }

    /**
     * Test attribute "extension_keys"
     */
    public function testPropertyExtensionKeys()
    {
    }

    /**
     * Test attribute "iso3_country"
     */
    public function testPropertyIso3Country()
    {
    }

    /**
     * Test attribute "iso3_language"
     */
    public function testPropertyIso3Language()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "script"
     */
    public function testPropertyScript()
    {
    }

    /**
     * Test attribute "unicode_locale_attributes"
     */
    public function testPropertyUnicodeLocaleAttributes()
    {
    }

    /**
     * Test attribute "unicode_locale_keys"
     */
    public function testPropertyUnicodeLocaleKeys()
    {
    }

    /**
     * Test attribute "variant"
     */
    public function testPropertyVariant()
    {
    }
}
