<?php
/**
 * URITest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Recomax REST API
 *
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * URITest Class Doc Comment
 *
 * @category    Class
 * @description URI
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class URITest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "URI"
     */
    public function testURI()
    {
    }

    /**
     * Test attribute "absolute"
     */
    public function testPropertyAbsolute()
    {
    }

    /**
     * Test attribute "authority"
     */
    public function testPropertyAuthority()
    {
    }

    /**
     * Test attribute "fragment"
     */
    public function testPropertyFragment()
    {
    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {
    }

    /**
     * Test attribute "opaque"
     */
    public function testPropertyOpaque()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }

    /**
     * Test attribute "query"
     */
    public function testPropertyQuery()
    {
    }

    /**
     * Test attribute "raw_authority"
     */
    public function testPropertyRawAuthority()
    {
    }

    /**
     * Test attribute "raw_fragment"
     */
    public function testPropertyRawFragment()
    {
    }

    /**
     * Test attribute "raw_path"
     */
    public function testPropertyRawPath()
    {
    }

    /**
     * Test attribute "raw_query"
     */
    public function testPropertyRawQuery()
    {
    }

    /**
     * Test attribute "raw_scheme_specific_part"
     */
    public function testPropertyRawSchemeSpecificPart()
    {
    }

    /**
     * Test attribute "raw_user_info"
     */
    public function testPropertyRawUserInfo()
    {
    }

    /**
     * Test attribute "scheme"
     */
    public function testPropertyScheme()
    {
    }

    /**
     * Test attribute "scheme_specific_part"
     */
    public function testPropertySchemeSpecificPart()
    {
    }

    /**
     * Test attribute "user_info"
     */
    public function testPropertyUserInfo()
    {
    }
}
